on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Validate YAML file
        run: yamllint action.yml
      - name: Tag
        uses: martoc/action-tag@v0.3.3
      - name: Release on GitHub
        uses: martoc/action-release@v0
        if: ${{ github.event_name != 'pull_request' }}
