---
name: Tag and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Tag
        uses: martoc/action-tag@5f190712b812e799c8d5525b57473714f05ba1ff
      - name: Release on GitHub
        uses: martoc/action-release@v0
