---
name: Tag and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Tag
        uses: martoc/action-tag@819bfd3820d0486b24a6cca70c82a1f0e49120bf
      - name: Release on GitHub
        uses: martoc/action-release@v0
