---
name: Tag and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 10
          fetch-tags: true
      - name: Tag
        uses: martoc/action-tag@d1426274e546994413987dba1637c80f63f32d54
      - name: Release on GitHub
        uses: martoc/action-release@v0
